services:
  # nginx:
  #   image: nginx:1.27.0
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - cron-frontend
  #     - cron-backend
  #   networks:
  #     - nginx

  # cron-frontend:
  #   # change with frontend image
  #   image: nginx:1.27.0
  #   networks:
  #     - nginx

  cron-backend:
    image: cron-backend
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - backend
      - nginx

  postgres:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
  nginx: