services:
  nginx:
    image: nginx:1.27.0
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - cron-frontend
      - cron-backend
    networks:
      - nginx

  cron-frontend:
    # change to frontend image
    image: nginx:1.27.0
    restart: unless-stopped
    networks:
      - nginx

  cron-backend:
    image: cron-backend
    restart: unless-stopped
    volumes:
      - ./.env:/usr/src/app/dist/.env:ro
    depends_on:
      - postgres
    networks:
      - backend
      - nginx

  postgres:
    image: postgres:16
    restart: unless-stopped
    env_file:
      - .db.env
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
  nginx: