services:
  postgres:
    image: postgres:16
    env_file:
      - .db.env
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
  nginx:
